"""Scenario registry: SSVI surface draws paired with Heston dynamics, plus Heston market families."""
import dataclasses
from dataclasses import dataclass

import numpy as np

from ..market.dupire import DupireSurface
from ..market.heston import heston_call, heston_iv
from ..market.local_vol import SSVILocalVol
from ..market.ssvi import SSVIParams, implied_vol_ssvi, no_arb_ok
from ..simulate.dynamics import HestonParams

XIS, RHOS, KAPPAS = (0.3, 0.6, 1.0), (-0.7, -0.3), (1.0, 2.0, 3.0)


@dataclass(frozen=True)
class ScenarioSpec:
    sid: str
    ssvi: SSVIParams
    dynamics: HestonParams
    s0: float = 1.0
    T: float = 2.0
    maturities: tuple = (0.25, 0.5, 1.0, 2.0)
    family: str = "ssvi"

    def local_vol(self):
        return SSVILocalVol(self.ssvi, self.s0, T_max=self.T)

    def target_ivs(self, k_grid, maturities):
        return np.stack([implied_vol_ssvi(self.ssvi, np.asarray(k_grid), t) for t in maturities])

    def as_params(self):
        p = {f"scenario.ssvi.{k}": v for k, v in dataclasses.asdict(self.ssvi).items()}
        p.update({f"scenario.dynamics.{k}": v for k, v in self.dynamics.to_dict().items()})
        p.update({"scenario.family": self.family, "scenario.s0": self.s0, "scenario.T": self.T,
                  "scenario.maturities": str(list(self.maturities))})
        return p


@dataclass(frozen=True)
class HestonMarketSpec:
    """Target surface generated by a Heston market; the calibrated model has its own dynamics."""
    sid: str
    market: HestonParams
    dynamics: HestonParams
    s0: float = 1.0
    T: float = 1.0
    maturities: tuple = (1.0,)
    k_lo: float = -0.9
    k_hi: float = 0.9
    n_k: int = 121
    t_lo: float = 0.02
    n_t: int = 50
    family: str = "heston"

    def local_vol(self):
        m = self.market
        T_grid = np.linspace(self.t_lo, self.T, self.n_t)
        k_grid = np.linspace(self.k_lo, self.k_hi, self.n_k)

        def price_fn(K, T):
            return heston_call(K, T, m.v0, m.kappa, m.theta, m.xi, m.rho, self.s0)

        return DupireSurface.from_price_fn(price_fn, self.s0, T_grid, k_grid)

    def target_ivs(self, k_grid, maturities):
        return np.stack([heston_iv(k_grid, t, self.market, self.s0) for t in maturities])

    def as_params(self):
        p = {f"scenario.market.{k}": v for k, v in self.market.to_dict().items()}
        p.update({f"scenario.dynamics.{k}": v for k, v in self.dynamics.to_dict().items()})
        p.update({"scenario.family": self.family, "scenario.s0": self.s0, "scenario.T": self.T,
                  "scenario.maturities": str(list(self.maturities))})
        return p


def quote_k_grid():
    return np.log(np.geomspace(0.6, 1.6, 13))


def _draw_ssvi(rng):
    for _ in range(100):
        p = SSVIParams(sigma0=rng.uniform(0.12, 0.35), eta=rng.uniform(0.5, 2.0),
                       gamma=rng.uniform(0.3, 0.5), rho=rng.uniform(-0.85, -0.1))
        if no_arb_ok(p):
            return p
    raise RuntimeError("no-arb resampling exhausted")


def make_registry():
    reg = {}
    for i in range(1, 21):
        rng = np.random.default_rng(1000 + i)
        p = _draw_ssvi(rng)
        dyn = HestonParams(kappa=float(rng.choice(KAPPAS)), theta=p.sigma0 ** 2,
                           xi=float(rng.choice(XIS)), rho=float(rng.choice(RHOS)),
                           v0=p.sigma0 ** 2)
        reg[f"s{i:02d}"] = ScenarioSpec(f"s{i:02d}", p, dyn)
    return reg


def fig3_registry():
    base = make_registry()["s01"]
    reg = {}
    for xi in XIS:
        for rho in RHOS:
            sid = f"f_xi{xi}_rho{rho}"
            dyn = dataclasses.replace(base.dynamics, xi=xi, rho=rho)
            reg[sid] = ScenarioSpec(sid, base.ssvi, dyn)
    return reg


def heston_registry():
    li_market = HestonParams(1.5768, 0.0484, 0.5751, -0.7, 0.1024)
    return {
        "li_simple": HestonMarketSpec("li_simple", li_market, HestonParams(1.5768, 0.0484, 0.5751, -0.5, 0.1024)),
        "li_complex": HestonMarketSpec("li_complex", li_market, HestonParams(1.0, 0.0144, 0.5751, 0.0, 0.0144)),
        "bayer": HestonMarketSpec("bayer", HestonParams(2.19, 0.17023, 1.04, -0.83, 0.0045),
                                  HestonParams(1.0, 0.0144, 0.5751, -0.9, 0.0144)),
    }


def full_registry():
    return {**make_registry(), **fig3_registry(), **heston_registry()}
